//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URS_Client.ServiceReferenceTBIS {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://main.realkreditnettet.dk")]
    public partial class error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private errorLocations errorLocationsField;
        
        private object errordetailsField;
        
        private string logcorrelationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public errorLocations errorLocations {
            get {
                return this.errorLocationsField;
            }
            set {
                this.errorLocationsField = value;
                this.RaisePropertyChanged("errorLocations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object errordetails {
            get {
                return this.errordetailsField;
            }
            set {
                this.errordetailsField = value;
                this.RaisePropertyChanged("errordetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string logcorrelation {
            get {
                return this.logcorrelationField;
            }
            set {
                this.logcorrelationField = value;
                this.RaisePropertyChanged("logcorrelation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public enum errorLocations {
        
        /// <remarks/>
        Body,
        
        /// <remarks/>
        Header,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class SimpleValidatePartyResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool validField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("valid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidatePartyResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogMessageResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangePasswordResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StatusTextResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionBinaryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransactionReponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public abstract partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int backEndStatusCodeField;
        
        private string backEndStatusTextField;
        
        private string backEndRootCauseField;
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int backEndStatusCode {
            get {
                return this.backEndStatusCodeField;
            }
            set {
                this.backEndStatusCodeField = value;
                this.RaisePropertyChanged("backEndStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string backEndStatusText {
            get {
                return this.backEndStatusTextField;
            }
            set {
                this.backEndStatusTextField = value;
                this.RaisePropertyChanged("backEndStatusText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string backEndRootCause {
            get {
                return this.backEndRootCauseField;
            }
            set {
                this.backEndRootCauseField = value;
                this.RaisePropertyChanged("backEndRootCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class ValidatePartyResponse : Response {
        
        private string rknetidField;
        
        private string[] outInfoflowsField;
        
        private int passwordExpireDaysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string rknetid {
            get {
                return this.rknetidField;
            }
            set {
                this.rknetidField = value;
                this.RaisePropertyChanged("rknetid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] outInfoflows {
            get {
                return this.outInfoflowsField;
            }
            set {
                this.outInfoflowsField = value;
                this.RaisePropertyChanged("outInfoflows");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int passwordExpireDays {
            get {
                return this.passwordExpireDaysField;
            }
            set {
                this.passwordExpireDaysField = value;
                this.RaisePropertyChanged("passwordExpireDays");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class LogMessageResponse : Response {
        
        private string logMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string logMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
                this.RaisePropertyChanged("logMessage");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class ChangePasswordResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class StatusTextResponse : Response {
        
        private string statusField;
        
        private int codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class TransactionBinaryResponse : Response {
        
        private byte[] resultBinaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] resultBinary {
            get {
                return this.resultBinaryField;
            }
            set {
                this.resultBinaryField = value;
                this.RaisePropertyChanged("resultBinary");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.realkreditnettet.dk")]
    public partial class TransactionReponse : Response {
        
        private string resultStringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string resultString {
            get {
                return this.resultStringField;
            }
            set {
                this.resultStringField = value;
                this.RaisePropertyChanged("resultString");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://main.realkreditnettet.dk", ConfigurationName="ServiceReferenceTBIS.Main")]
    public interface Main {
        
        // CODEGEN: Parameter 'doTransactionReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="doTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="doTransactionReturn")]
        URS_Client.ServiceReferenceTBIS.doTransactionResponse doTransaction(URS_Client.ServiceReferenceTBIS.doTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="doTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionResponse> doTransactionAsync(URS_Client.ServiceReferenceTBIS.doTransactionRequest request);
        
        // CODEGEN: Parameter 'doTransactionBinaryReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="doTransactionBinary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="doTransactionBinaryReturn")]
        URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse doTransactionBinary(URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="doTransactionBinary", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse> doTransactionBinaryAsync(URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest request);
        
        // CODEGEN: Parameter 'getStatusTextReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getStatusText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getStatusTextReturn")]
        URS_Client.ServiceReferenceTBIS.getStatusTextResponse getStatusText(URS_Client.ServiceReferenceTBIS.getStatusTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getStatusText", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getStatusTextResponse> getStatusTextAsync(URS_Client.ServiceReferenceTBIS.getStatusTextRequest request);
        
        // CODEGEN: Parameter 'changePasswordReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="changePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        URS_Client.ServiceReferenceTBIS.changePasswordResponse1 changePassword(URS_Client.ServiceReferenceTBIS.changePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="changePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.changePasswordResponse1> changePasswordAsync(URS_Client.ServiceReferenceTBIS.changePasswordRequest request);
        
        // CODEGEN: Parameter 'getLogMessageReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="getLogMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getLogMessageReturn")]
        URS_Client.ServiceReferenceTBIS.getLogMessageResponse getLogMessage(URS_Client.ServiceReferenceTBIS.getLogMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="getLogMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getLogMessageResponse> getLogMessageAsync(URS_Client.ServiceReferenceTBIS.getLogMessageRequest request);
        
        // CODEGEN: Parameter 'validatePartyReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="validateParty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="validatePartyReturn")]
        URS_Client.ServiceReferenceTBIS.validatePartyResponse1 validateParty(URS_Client.ServiceReferenceTBIS.validatePartyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="validateParty", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.validatePartyResponse1> validatePartyAsync(URS_Client.ServiceReferenceTBIS.validatePartyRequest request);
        
        // CODEGEN: Parameter 'simpleValidatePartyReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="simpleValidateParty", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(URS_Client.ServiceReferenceTBIS.error), Action="simpleValidateParty", Name="error")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Response))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="simpleValidatePartyReturn")]
        URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1 simpleValidateParty(URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="simpleValidateParty", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1> simpleValidatePartyAsync(URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doTransaction", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class doTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serverid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string query;
        
        public doTransactionRequest() {
        }
        
        public doTransactionRequest(string partyid, string password, string flowname, string serverid, string query) {
            this.partyid = partyid;
            this.password = password;
            this.flowname = flowname;
            this.serverid = serverid;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doTransactionResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class doTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.TransactionReponse doTransactionReturn;
        
        public doTransactionResponse() {
        }
        
        public doTransactionResponse(URS_Client.ServiceReferenceTBIS.TransactionReponse doTransactionReturn) {
            this.doTransactionReturn = doTransactionReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doTransactionBinary", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class doTransactionBinaryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string flowname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serverid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] query;
        
        public doTransactionBinaryRequest() {
        }
        
        public doTransactionBinaryRequest(string partyid, string password, string flowname, string serverid, byte[] query) {
            this.partyid = partyid;
            this.password = password;
            this.flowname = flowname;
            this.serverid = serverid;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="doTransactionBinaryResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class doTransactionBinaryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.TransactionBinaryResponse doTransactionBinaryReturn;
        
        public doTransactionBinaryResponse() {
        }
        
        public doTransactionBinaryResponse(URS_Client.ServiceReferenceTBIS.TransactionBinaryResponse doTransactionBinaryReturn) {
            this.doTransactionBinaryReturn = doTransactionBinaryReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusText", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class getStatusTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code;
        
        public getStatusTextRequest() {
        }
        
        public getStatusTextRequest(int code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStatusTextResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class getStatusTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.StatusTextResponse getStatusTextReturn;
        
        public getStatusTextResponse() {
        }
        
        public getStatusTextResponse(URS_Client.ServiceReferenceTBIS.StatusTextResponse getStatusTextReturn) {
            this.getStatusTextReturn = getStatusTextReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePassword", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string newpassword;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string confirmpassword;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(string partyid, string password, string newpassword, string confirmpassword) {
            this.partyid = partyid;
            this.password = password;
            this.newpassword = newpassword;
            this.confirmpassword = confirmpassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="changePasswordResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class changePasswordResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.ChangePasswordResponse changePasswordReturn;
        
        public changePasswordResponse1() {
        }
        
        public changePasswordResponse1(URS_Client.ServiceReferenceTBIS.ChangePasswordResponse changePasswordReturn) {
            this.changePasswordReturn = changePasswordReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLogMessage", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class getLogMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int logid;
        
        public getLogMessageRequest() {
        }
        
        public getLogMessageRequest(string partyid, string password, int logid) {
            this.partyid = partyid;
            this.password = password;
            this.logid = logid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getLogMessageResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class getLogMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.LogMessageResponse getLogMessageReturn;
        
        public getLogMessageResponse() {
        }
        
        public getLogMessageResponse(URS_Client.ServiceReferenceTBIS.LogMessageResponse getLogMessageReturn) {
            this.getLogMessageReturn = getLogMessageReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateParty", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class validatePartyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string password;
        
        public validatePartyRequest() {
        }
        
        public validatePartyRequest(string partyid, string password) {
            this.partyid = partyid;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validatePartyResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class validatePartyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public URS_Client.ServiceReferenceTBIS.ValidatePartyResponse validatePartyReturn;
        
        public validatePartyResponse1() {
        }
        
        public validatePartyResponse1(URS_Client.ServiceReferenceTBIS.ValidatePartyResponse validatePartyReturn) {
            this.validatePartyReturn = validatePartyReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="simpleValidateParty", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class simpleValidatePartyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string partyid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public simpleValidatePartyRequest() {
        }
        
        public simpleValidatePartyRequest(string partyid, string password) {
            this.partyid = partyid;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="simpleValidatePartyResponse", WrapperNamespace="http://main.realkreditnettet.dk", IsWrapped=true)]
    public partial class simpleValidatePartyResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://main.realkreditnettet.dk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public URS_Client.ServiceReferenceTBIS.SimpleValidatePartyResponse simpleValidatePartyReturn;
        
        public simpleValidatePartyResponse1() {
        }
        
        public simpleValidatePartyResponse1(URS_Client.ServiceReferenceTBIS.SimpleValidatePartyResponse simpleValidatePartyReturn) {
            this.simpleValidatePartyReturn = simpleValidatePartyReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MainChannel : URS_Client.ServiceReferenceTBIS.Main, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MainClient : System.ServiceModel.ClientBase<URS_Client.ServiceReferenceTBIS.Main>, URS_Client.ServiceReferenceTBIS.Main {
        
        public MainClient() {
        }
        
        public MainClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MainClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MainClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.doTransactionResponse URS_Client.ServiceReferenceTBIS.Main.doTransaction(URS_Client.ServiceReferenceTBIS.doTransactionRequest request) {
            return base.Channel.doTransaction(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.TransactionReponse doTransaction(string partyid, string password, string flowname, string serverid, string query) {
            URS_Client.ServiceReferenceTBIS.doTransactionRequest inValue = new URS_Client.ServiceReferenceTBIS.doTransactionRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.flowname = flowname;
            inValue.serverid = serverid;
            inValue.query = query;
            URS_Client.ServiceReferenceTBIS.doTransactionResponse retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).doTransaction(inValue);
            return retVal.doTransactionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionResponse> URS_Client.ServiceReferenceTBIS.Main.doTransactionAsync(URS_Client.ServiceReferenceTBIS.doTransactionRequest request) {
            return base.Channel.doTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionResponse> doTransactionAsync(string partyid, string password, string flowname, string serverid, string query) {
            URS_Client.ServiceReferenceTBIS.doTransactionRequest inValue = new URS_Client.ServiceReferenceTBIS.doTransactionRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.flowname = flowname;
            inValue.serverid = serverid;
            inValue.query = query;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).doTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse URS_Client.ServiceReferenceTBIS.Main.doTransactionBinary(URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest request) {
            return base.Channel.doTransactionBinary(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.TransactionBinaryResponse doTransactionBinary(string partyid, string password, string flowname, string serverid, byte[] query) {
            URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest inValue = new URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.flowname = flowname;
            inValue.serverid = serverid;
            inValue.query = query;
            URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).doTransactionBinary(inValue);
            return retVal.doTransactionBinaryReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse> URS_Client.ServiceReferenceTBIS.Main.doTransactionBinaryAsync(URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest request) {
            return base.Channel.doTransactionBinaryAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.doTransactionBinaryResponse> doTransactionBinaryAsync(string partyid, string password, string flowname, string serverid, byte[] query) {
            URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest inValue = new URS_Client.ServiceReferenceTBIS.doTransactionBinaryRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.flowname = flowname;
            inValue.serverid = serverid;
            inValue.query = query;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).doTransactionBinaryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.getStatusTextResponse URS_Client.ServiceReferenceTBIS.Main.getStatusText(URS_Client.ServiceReferenceTBIS.getStatusTextRequest request) {
            return base.Channel.getStatusText(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.StatusTextResponse getStatusText(int code) {
            URS_Client.ServiceReferenceTBIS.getStatusTextRequest inValue = new URS_Client.ServiceReferenceTBIS.getStatusTextRequest();
            inValue.code = code;
            URS_Client.ServiceReferenceTBIS.getStatusTextResponse retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).getStatusText(inValue);
            return retVal.getStatusTextReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getStatusTextResponse> URS_Client.ServiceReferenceTBIS.Main.getStatusTextAsync(URS_Client.ServiceReferenceTBIS.getStatusTextRequest request) {
            return base.Channel.getStatusTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getStatusTextResponse> getStatusTextAsync(int code) {
            URS_Client.ServiceReferenceTBIS.getStatusTextRequest inValue = new URS_Client.ServiceReferenceTBIS.getStatusTextRequest();
            inValue.code = code;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).getStatusTextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.changePasswordResponse1 URS_Client.ServiceReferenceTBIS.Main.changePassword(URS_Client.ServiceReferenceTBIS.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.ChangePasswordResponse changePassword(string partyid, string password, string newpassword, string confirmpassword) {
            URS_Client.ServiceReferenceTBIS.changePasswordRequest inValue = new URS_Client.ServiceReferenceTBIS.changePasswordRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.newpassword = newpassword;
            inValue.confirmpassword = confirmpassword;
            URS_Client.ServiceReferenceTBIS.changePasswordResponse1 retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).changePassword(inValue);
            return retVal.changePasswordReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.changePasswordResponse1> URS_Client.ServiceReferenceTBIS.Main.changePasswordAsync(URS_Client.ServiceReferenceTBIS.changePasswordRequest request) {
            return base.Channel.changePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.changePasswordResponse1> changePasswordAsync(string partyid, string password, string newpassword, string confirmpassword) {
            URS_Client.ServiceReferenceTBIS.changePasswordRequest inValue = new URS_Client.ServiceReferenceTBIS.changePasswordRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.newpassword = newpassword;
            inValue.confirmpassword = confirmpassword;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).changePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.getLogMessageResponse URS_Client.ServiceReferenceTBIS.Main.getLogMessage(URS_Client.ServiceReferenceTBIS.getLogMessageRequest request) {
            return base.Channel.getLogMessage(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.LogMessageResponse getLogMessage(string partyid, string password, int logid) {
            URS_Client.ServiceReferenceTBIS.getLogMessageRequest inValue = new URS_Client.ServiceReferenceTBIS.getLogMessageRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.logid = logid;
            URS_Client.ServiceReferenceTBIS.getLogMessageResponse retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).getLogMessage(inValue);
            return retVal.getLogMessageReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getLogMessageResponse> URS_Client.ServiceReferenceTBIS.Main.getLogMessageAsync(URS_Client.ServiceReferenceTBIS.getLogMessageRequest request) {
            return base.Channel.getLogMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.getLogMessageResponse> getLogMessageAsync(string partyid, string password, int logid) {
            URS_Client.ServiceReferenceTBIS.getLogMessageRequest inValue = new URS_Client.ServiceReferenceTBIS.getLogMessageRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            inValue.logid = logid;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).getLogMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.validatePartyResponse1 URS_Client.ServiceReferenceTBIS.Main.validateParty(URS_Client.ServiceReferenceTBIS.validatePartyRequest request) {
            return base.Channel.validateParty(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.ValidatePartyResponse validateParty(string partyid, string password) {
            URS_Client.ServiceReferenceTBIS.validatePartyRequest inValue = new URS_Client.ServiceReferenceTBIS.validatePartyRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            URS_Client.ServiceReferenceTBIS.validatePartyResponse1 retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).validateParty(inValue);
            return retVal.validatePartyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.validatePartyResponse1> URS_Client.ServiceReferenceTBIS.Main.validatePartyAsync(URS_Client.ServiceReferenceTBIS.validatePartyRequest request) {
            return base.Channel.validatePartyAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.validatePartyResponse1> validatePartyAsync(string partyid, string password) {
            URS_Client.ServiceReferenceTBIS.validatePartyRequest inValue = new URS_Client.ServiceReferenceTBIS.validatePartyRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).validatePartyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1 URS_Client.ServiceReferenceTBIS.Main.simpleValidateParty(URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest request) {
            return base.Channel.simpleValidateParty(request);
        }
        
        public URS_Client.ServiceReferenceTBIS.SimpleValidatePartyResponse simpleValidateParty(string partyid, string password) {
            URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest inValue = new URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1 retVal = ((URS_Client.ServiceReferenceTBIS.Main)(this)).simpleValidateParty(inValue);
            return retVal.simpleValidatePartyReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1> URS_Client.ServiceReferenceTBIS.Main.simpleValidatePartyAsync(URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest request) {
            return base.Channel.simpleValidatePartyAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceTBIS.simpleValidatePartyResponse1> simpleValidatePartyAsync(string partyid, string password) {
            URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest inValue = new URS_Client.ServiceReferenceTBIS.simpleValidatePartyRequest();
            inValue.partyid = partyid;
            inValue.password = password;
            return ((URS_Client.ServiceReferenceTBIS.Main)(this)).simpleValidatePartyAsync(inValue);
        }
    }
}
