//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace URS_Client.ServiceReferenceEVurdering {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efpi.dk/basis/xml/schemas/2007/07/01/")]
    public partial class eFPIDetailsErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private errorLocations errorlocationField;
        
        private object errordetailsField;
        
        private string logcorrelationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public errorLocations errorlocation {
            get {
                return this.errorlocationField;
            }
            set {
                this.errorlocationField = value;
                this.RaisePropertyChanged("errorlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object errordetails {
            get {
                return this.errordetailsField;
            }
            set {
                this.errordetailsField = value;
                this.RaisePropertyChanged("errordetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string logcorrelation {
            get {
                return this.logcorrelationField;
            }
            set {
                this.logcorrelationField = value;
                this.RaisePropertyChanged("logcorrelation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efpi.dk/basis/xml/schemas/2007/07/01/")]
    public enum errorLocations {
        
        /// <remarks/>
        Body,
        
        /// <remarks/>
        Header,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class PrisModelTilmelding : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime datoField;
        
        private string partIdField;
        
        private int systemleverandoerNummerField;
        
        private PrisModelType prisModelField;
        
        private System.Nullable<System.DateTime> udfoertDatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
                this.RaisePropertyChanged("Dato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SystemleverandoerNummer {
            get {
                return this.systemleverandoerNummerField;
            }
            set {
                this.systemleverandoerNummerField = value;
                this.RaisePropertyChanged("SystemleverandoerNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PrisModelType PrisModel {
            get {
                return this.prisModelField;
            }
            set {
                this.prisModelField = value;
                this.RaisePropertyChanged("PrisModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> UdfoertDato {
            get {
                return this.udfoertDatoField;
            }
            set {
                this.udfoertDatoField = value;
                this.RaisePropertyChanged("UdfoertDato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public enum PrisModelType {
        
        /// <remarks/>
        Transaktion,
        
        /// <remarks/>
        Edokumentation,
        
        /// <remarks/>
        Suspenderet,
        
        /// <remarks/>
        IkkeSat,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class PrisModelHentResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool erSuspenderetNuField;
        
        private PrisModelTilmelding tilmeldingAktivPaaDatoField;
        
        private PrisModelTilmelding afventendeTilmeldingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool ErSuspenderetNu {
            get {
                return this.erSuspenderetNuField;
            }
            set {
                this.erSuspenderetNuField = value;
                this.RaisePropertyChanged("ErSuspenderetNu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PrisModelTilmelding TilmeldingAktivPaaDato {
            get {
                return this.tilmeldingAktivPaaDatoField;
            }
            set {
                this.tilmeldingAktivPaaDatoField = value;
                this.RaisePropertyChanged("TilmeldingAktivPaaDato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PrisModelTilmelding AfventendeTilmelding {
            get {
                return this.afventendeTilmeldingField;
            }
            set {
                this.afventendeTilmeldingField = value;
                this.RaisePropertyChanged("AfventendeTilmelding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class PrisModelHentRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partIdField;
        
        private System.DateTime datoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
                this.RaisePropertyChanged("Dato");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class FindesHaendelseResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool findesHaendelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool FindesHaendelse {
            get {
                return this.findesHaendelseField;
            }
            set {
                this.findesHaendelseField = value;
                this.RaisePropertyChanged("FindesHaendelse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class FindesHaendelseRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partIdField;
        
        private SagsnummerIdentifikatorType ejendomsmaeglerSagsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SagsnummerIdentifikatorType EjendomsmaeglerSagsnummer {
            get {
                return this.ejendomsmaeglerSagsnummerField;
            }
            set {
                this.ejendomsmaeglerSagsnummerField = value;
                this.RaisePropertyChanged("EjendomsmaeglerSagsnummer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efpi.dk/ehp2011/xml/schemas/EFPI_SagsnummerIdentifikator_v1")]
    public partial class SagsnummerIdentifikatorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class HaendelseIndsendResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class AmetaInformationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partIdField;
        
        private SagsnummerIdentifikatorType ejendomsmaeglerSagsnummerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SagsnummerIdentifikatorType EjendomsmaeglerSagsnummer {
            get {
                return this.ejendomsmaeglerSagsnummerField;
            }
            set {
                this.ejendomsmaeglerSagsnummerField = value;
                this.RaisePropertyChanged("EjendomsmaeglerSagsnummer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class HaendelseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AmetaInformationType ametaInformationField;
        
        private HaendelsestypeType haendelsestypeField;
        
        private bool haendelsestypeFieldSpecified;
        
        private System.DateTime haendelseDatoField;
        
        private RealPropertyStructureType realPropertyStructureField;
        
        private EjendomstypeType ejendomsTypeField;
        
        private SagsnummerIdentifikatorType ejendomsmaeglerSagsnummerField;
        
        private AddressPostalType addressPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AmetaInformationType AmetaInformation {
            get {
                return this.ametaInformationField;
            }
            set {
                this.ametaInformationField = value;
                this.RaisePropertyChanged("AmetaInformation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HaendelsestypeType Haendelsestype {
            get {
                return this.haendelsestypeField;
            }
            set {
                this.haendelsestypeField = value;
                this.RaisePropertyChanged("Haendelsestype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HaendelsestypeSpecified {
            get {
                return this.haendelsestypeFieldSpecified;
            }
            set {
                this.haendelsestypeFieldSpecified = value;
                this.RaisePropertyChanged("HaendelsestypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime HaendelseDato {
            get {
                return this.haendelseDatoField;
            }
            set {
                this.haendelseDatoField = value;
                this.RaisePropertyChanged("HaendelseDato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/bbr.dk/xml/schemas/2005/12/15/", Order=3)]
        public RealPropertyStructureType RealPropertyStructure {
            get {
                return this.realPropertyStructureField;
            }
            set {
                this.realPropertyStructureField = value;
                this.RaisePropertyChanged("RealPropertyStructure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public EjendomstypeType EjendomsType {
            get {
                return this.ejendomsTypeField;
            }
            set {
                this.ejendomsTypeField = value;
                this.RaisePropertyChanged("EjendomsType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public SagsnummerIdentifikatorType EjendomsmaeglerSagsnummer {
            get {
                return this.ejendomsmaeglerSagsnummerField;
            }
            set {
                this.ejendomsmaeglerSagsnummerField = value;
                this.RaisePropertyChanged("EjendomsmaeglerSagsnummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/", Order=6)]
        public AddressPostalType AddressPostal {
            get {
                return this.addressPostalField;
            }
            set {
                this.addressPostalField = value;
                this.RaisePropertyChanged("AddressPostal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public enum HaendelsestypeType {
        
        /// <remarks/>
        SatTilSalg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/bbr.dk/xml/schemas/2005/12/15/")]
    public partial class RealPropertyStructureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string municipalRealPropertyIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/bbr.dk/xml/schemas/2005/03/11/", Order=1)]
        public string MunicipalRealPropertyIdentifier {
            get {
                return this.municipalRealPropertyIdentifierField;
            }
            set {
                this.municipalRealPropertyIdentifierField = value;
                this.RaisePropertyChanged("MunicipalRealPropertyIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public enum EjendomstypeType {
        
        /// <remarks/>
        Bolig,
        
        /// <remarks/>
        Erhverv,
        
        /// <remarks/>
        Andel,
        
        /// <remarks/>
        Grund,
        
        /// <remarks/>
        Landejendom,
        
        /// <remarks/>
        Fritidshus,
        
        /// <remarks/>
        Fritidsgrund,
        
        /// <remarks/>
        Villalejlighed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressPostalType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mailDeliverySublocationIdentifierField;
        
        private string streetNameField;
        
        private string streetNameForAddressingNameField;
        
        private string streetBuildingIdentifierField;
        
        private string floorIdentifierField;
        
        private string suiteIdentifierField;
        
        private string districtSubdivisionIdentifierField;
        
        private string postOfficeBoxIdentifierField;
        
        private string postCodeIdentifierField;
        
        private string districtNameField;
        
        private CountryIdentificationCodeType countryIdentificationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=0)]
        public string MailDeliverySublocationIdentifier {
            get {
                return this.mailDeliverySublocationIdentifierField;
            }
            set {
                this.mailDeliverySublocationIdentifierField = value;
                this.RaisePropertyChanged("MailDeliverySublocationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=1)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
                this.RaisePropertyChanged("StreetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=2)]
        public string StreetNameForAddressingName {
            get {
                return this.streetNameForAddressingNameField;
            }
            set {
                this.streetNameForAddressingNameField = value;
                this.RaisePropertyChanged("StreetNameForAddressingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=3)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=4)]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
                this.RaisePropertyChanged("FloorIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=5)]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
                this.RaisePropertyChanged("SuiteIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=6)]
        public string DistrictSubdivisionIdentifier {
            get {
                return this.districtSubdivisionIdentifierField;
            }
            set {
                this.districtSubdivisionIdentifierField = value;
                this.RaisePropertyChanged("DistrictSubdivisionIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/05/13/", DataType="integer", Order=7)]
        public string PostOfficeBoxIdentifier {
            get {
                return this.postOfficeBoxIdentifierField;
            }
            set {
                this.postOfficeBoxIdentifierField = value;
                this.RaisePropertyChanged("PostOfficeBoxIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=8)]
        public string PostCodeIdentifier {
            get {
                return this.postCodeIdentifierField;
            }
            set {
                this.postCodeIdentifierField = value;
                this.RaisePropertyChanged("PostCodeIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2005/03/15/", Order=9)]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
                this.RaisePropertyChanged("DistrictName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=10)]
        public CountryIdentificationCodeType CountryIdentificationCode {
            get {
                return this.countryIdentificationCodeField;
            }
            set {
                this.countryIdentificationCodeField = value;
                this.RaisePropertyChanged("CountryIdentificationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public partial class CountryIdentificationCodeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private _CountryIdentificationSchemeType schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public _CountryIdentificationSchemeType scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
                this.RaisePropertyChanged("scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/")]
    public enum _CountryIdentificationSchemeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha2")]
        iso3166alpha2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("iso3166-alpha3")]
        iso3166alpha3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("un-numeric3")]
        unnumeric3,
        
        /// <remarks/>
        imk,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class HaendelseIndsendRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partIdField;
        
        private int systemleverandoerNummerField;
        
        private HaendelseType haendelseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SystemleverandoerNummer {
            get {
                return this.systemleverandoerNummerField;
            }
            set {
                this.systemleverandoerNummerField = value;
                this.RaisePropertyChanged("SystemleverandoerNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public HaendelseType Haendelse {
            get {
                return this.haendelseField;
            }
            set {
                this.haendelseField = value;
                this.RaisePropertyChanged("Haendelse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressCompleteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressAccessType addressAccessField;
        
        private AddressPostalType addressPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", Order=0)]
        public AddressAccessType AddressAccess {
            get {
                return this.addressAccessField;
            }
            set {
                this.addressAccessField = value;
                this.RaisePropertyChanged("AddressAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AddressPostalType AddressPostal {
            get {
                return this.addressPostalField;
            }
            set {
                this.addressPostalField = value;
                this.RaisePropertyChanged("AddressPostal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/")]
    public partial class AddressAccessType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string streetCodeField;
        
        private string streetBuildingIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=1)]
        public string StreetCode {
            get {
                return this.streetCodeField;
            }
            set {
                this.streetCodeField = value;
                this.RaisePropertyChanged("StreetCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=2)]
        public string StreetBuildingIdentifier {
            get {
                return this.streetBuildingIdentifierField;
            }
            set {
                this.streetBuildingIdentifierField = value;
                this.RaisePropertyChanged("StreetBuildingIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/bbr.dk/xml/schemas/2005/03/11/")]
    public partial class RealPropertyIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string municipalityCodeField;
        
        private string municipalRealPropertyIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/cpr.dk/xml/schemas/core/2005/03/18/", Order=0)]
        public string MunicipalityCode {
            get {
                return this.municipalityCodeField;
            }
            set {
                this.municipalityCodeField = value;
                this.RaisePropertyChanged("MunicipalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MunicipalRealPropertyIdentifier {
            get {
                return this.municipalRealPropertyIdentifierField;
            }
            set {
                this.municipalRealPropertyIdentifierField = value;
                this.RaisePropertyChanged("MunicipalRealPropertyIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://efpi.dk/basis/xml/schemas/2007/07/01/")]
    public partial class eFPIfejlType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fejlkodeField;
        
        private string fejluddybningField;
        
        private string faultactorField;
        
        private object xmldetajlerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fejlkode {
            get {
                return this.fejlkodeField;
            }
            set {
                this.fejlkodeField = value;
                this.RaisePropertyChanged("fejlkode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fejluddybning {
            get {
                return this.fejluddybningField;
            }
            set {
                this.fejluddybningField = value;
                this.RaisePropertyChanged("fejluddybning");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=2)]
        public string faultactor {
            get {
                return this.faultactorField;
            }
            set {
                this.faultactorField = value;
                this.RaisePropertyChanged("faultactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object xmldetajler {
            get {
                return this.xmldetajlerField;
            }
            set {
                this.xmldetajlerField = value;
                this.RaisePropertyChanged("xmldetajler");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2006/01/06/")]
    public partial class AddressSpecificType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AddressAccessType addressAccessField;
        
        private string floorIdentifierField;
        
        private string suiteIdentifierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/xkom.dk/xml/schemas/2005/03/15/", Order=0)]
        public AddressAccessType AddressAccess {
            get {
                return this.addressAccessField;
            }
            set {
                this.addressAccessField = value;
                this.RaisePropertyChanged("AddressAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=1)]
        public string FloorIdentifier {
            get {
                return this.floorIdentifierField;
            }
            set {
                this.floorIdentifierField = value;
                this.RaisePropertyChanged("FloorIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://rep.oio.dk/ebxml/xml/schemas/dkcc/2003/02/13/", Order=2)]
        public string SuiteIdentifier {
            get {
                return this.suiteIdentifierField;
            }
            set {
                this.suiteIdentifierField = value;
                this.RaisePropertyChanged("SuiteIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class PrisModelTilmeldResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
    public partial class PrisModelTilmeldRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string partIdField;
        
        private int systemleverandoerNummerField;
        
        private PrisModelType prisModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PartId {
            get {
                return this.partIdField;
            }
            set {
                this.partIdField = value;
                this.RaisePropertyChanged("PartId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SystemleverandoerNummer {
            get {
                return this.systemleverandoerNummerField;
            }
            set {
                this.systemleverandoerNummerField = value;
                this.RaisePropertyChanged("SystemleverandoerNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PrisModelType PrisModel {
            get {
                return this.prisModelField;
            }
            set {
                this.prisModelField = value;
                this.RaisePropertyChanged("PrisModel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="PrisModel.URS", Namespace="http://service.enettet.dk/2015/01/05/", ConfigurationName="ServiceReferenceEVurdering.PrisModelURS")]
    public interface PrisModelURS {
        
        // CODEGEN: Generating message contract since the operation PrisModelTilmeld is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelTilmeldRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(URS_Client.ServiceReferenceEVurdering.eFPIDetailsErrorType), Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelTilmeldRequest", Name="error", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressCompleteType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RealPropertyIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eFPIfejlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressSpecificType))]
        URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse PrisModelTilmeld(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelTilmeldRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse> PrisModelTilmeldAsync(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest request);
        
        // CODEGEN: Generating message contract since the operation HaendelseIndsend is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/HaendelseIndsendRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(URS_Client.ServiceReferenceEVurdering.eFPIDetailsErrorType), Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/HaendelseIndsendRequest", Name="error", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressCompleteType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RealPropertyIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eFPIfejlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressSpecificType))]
        URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse HaendelseIndsend(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/HaendelseIndsendRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse> HaendelseIndsendAsync(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest request);
        
        // CODEGEN: Generating message contract since the operation PrisModelHent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelHentRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(URS_Client.ServiceReferenceEVurdering.eFPIDetailsErrorType), Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelHentRequest", Name="error", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressCompleteType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RealPropertyIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eFPIfejlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressSpecificType))]
        URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse PrisModelHent(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/PrisModelHentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse> PrisModelHentAsync(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest request);
        
        // CODEGEN: Generating message contract since the operation FindesHaendelse is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/FindesHaendelseRequest", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(URS_Client.ServiceReferenceEVurdering.eFPIDetailsErrorType), Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/FindesHaendelseRequest", Name="error", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PrisModelHentRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(FindesHaendelseRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HaendelseIndsendRequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressCompleteType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RealPropertyIdentifierType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(eFPIfejlType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AddressSpecificType))]
        URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse FindesHaendelse(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.enettet.dk/2015/01/05/PrisModel.URS/FindesHaendelseRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse> FindesHaendelseAsync(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrisModelTilmeldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequestType PrisModelTilmeld;
        
        public PrisModelTilmeldRequest() {
        }
        
        public PrisModelTilmeldRequest(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequestType PrisModelTilmeld) {
            this.PrisModelTilmeld = PrisModelTilmeld;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrisModelTilmeldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrisModelTilmeldResponse", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponseType PrisModelTilmeldResponse1;
        
        public PrisModelTilmeldResponse() {
        }
        
        public PrisModelTilmeldResponse(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponseType PrisModelTilmeldResponse1) {
            this.PrisModelTilmeldResponse1 = PrisModelTilmeldResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaendelseIndsendRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequestType HaendelseIndsend;
        
        public HaendelseIndsendRequest() {
        }
        
        public HaendelseIndsendRequest(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequestType HaendelseIndsend) {
            this.HaendelseIndsend = HaendelseIndsend;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HaendelseIndsendResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HaendelseIndsendResponse", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponseType HaendelseIndsendResponse1;
        
        public HaendelseIndsendResponse() {
        }
        
        public HaendelseIndsendResponse(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponseType HaendelseIndsendResponse1) {
            this.HaendelseIndsendResponse1 = HaendelseIndsendResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrisModelHentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.PrisModelHentRequestType PrisModelHent;
        
        public PrisModelHentRequest() {
        }
        
        public PrisModelHentRequest(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequestType PrisModelHent) {
            this.PrisModelHent = PrisModelHent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PrisModelHentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PrisModelHentResponse", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.PrisModelHentResponseType PrisModelHentResponse1;
        
        public PrisModelHentResponse() {
        }
        
        public PrisModelHentResponse(URS_Client.ServiceReferenceEVurdering.PrisModelHentResponseType PrisModelHentResponse1) {
            this.PrisModelHentResponse1 = PrisModelHentResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindesHaendelseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequestType FindesHaendelse;
        
        public FindesHaendelseRequest() {
        }
        
        public FindesHaendelseRequest(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequestType FindesHaendelse) {
            this.FindesHaendelse = FindesHaendelse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindesHaendelseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindesHaendelseResponse", Namespace="http://enettet.dk/prismodel/xml/schemas/URS_PrisModel_v1", Order=0)]
        public URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponseType FindesHaendelseResponse1;
        
        public FindesHaendelseResponse() {
        }
        
        public FindesHaendelseResponse(URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponseType FindesHaendelseResponse1) {
            this.FindesHaendelseResponse1 = FindesHaendelseResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrisModelURSChannel : URS_Client.ServiceReferenceEVurdering.PrisModelURS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrisModelURSClient : System.ServiceModel.ClientBase<URS_Client.ServiceReferenceEVurdering.PrisModelURS>, URS_Client.ServiceReferenceEVurdering.PrisModelURS {
        
        public PrisModelURSClient() {
        }
        
        public PrisModelURSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrisModelURSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisModelURSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrisModelURSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse URS_Client.ServiceReferenceEVurdering.PrisModelURS.PrisModelTilmeld(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest request) {
            return base.Channel.PrisModelTilmeld(request);
        }
        
        public URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponseType PrisModelTilmeld(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequestType PrisModelTilmeld1) {
            URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest inValue = new URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest();
            inValue.PrisModelTilmeld = PrisModelTilmeld1;
            URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse retVal = ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).PrisModelTilmeld(inValue);
            return retVal.PrisModelTilmeldResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse> URS_Client.ServiceReferenceEVurdering.PrisModelURS.PrisModelTilmeldAsync(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest request) {
            return base.Channel.PrisModelTilmeldAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldResponse> PrisModelTilmeldAsync(URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequestType PrisModelTilmeld) {
            URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest inValue = new URS_Client.ServiceReferenceEVurdering.PrisModelTilmeldRequest();
            inValue.PrisModelTilmeld = PrisModelTilmeld;
            return ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).PrisModelTilmeldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse URS_Client.ServiceReferenceEVurdering.PrisModelURS.HaendelseIndsend(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest request) {
            return base.Channel.HaendelseIndsend(request);
        }
        
        public URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponseType HaendelseIndsend(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequestType HaendelseIndsend1) {
            URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest inValue = new URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest();
            inValue.HaendelseIndsend = HaendelseIndsend1;
            URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse retVal = ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).HaendelseIndsend(inValue);
            return retVal.HaendelseIndsendResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse> URS_Client.ServiceReferenceEVurdering.PrisModelURS.HaendelseIndsendAsync(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest request) {
            return base.Channel.HaendelseIndsendAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.HaendelseIndsendResponse> HaendelseIndsendAsync(URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequestType HaendelseIndsend) {
            URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest inValue = new URS_Client.ServiceReferenceEVurdering.HaendelseIndsendRequest();
            inValue.HaendelseIndsend = HaendelseIndsend;
            return ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).HaendelseIndsendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse URS_Client.ServiceReferenceEVurdering.PrisModelURS.PrisModelHent(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest request) {
            return base.Channel.PrisModelHent(request);
        }
        
        public URS_Client.ServiceReferenceEVurdering.PrisModelHentResponseType PrisModelHent(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequestType PrisModelHent1) {
            URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest inValue = new URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest();
            inValue.PrisModelHent = PrisModelHent1;
            URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse retVal = ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).PrisModelHent(inValue);
            return retVal.PrisModelHentResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse> URS_Client.ServiceReferenceEVurdering.PrisModelURS.PrisModelHentAsync(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest request) {
            return base.Channel.PrisModelHentAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.PrisModelHentResponse> PrisModelHentAsync(URS_Client.ServiceReferenceEVurdering.PrisModelHentRequestType PrisModelHent) {
            URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest inValue = new URS_Client.ServiceReferenceEVurdering.PrisModelHentRequest();
            inValue.PrisModelHent = PrisModelHent;
            return ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).PrisModelHentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse URS_Client.ServiceReferenceEVurdering.PrisModelURS.FindesHaendelse(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest request) {
            return base.Channel.FindesHaendelse(request);
        }
        
        public URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponseType FindesHaendelse(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequestType FindesHaendelse1) {
            URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest inValue = new URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest();
            inValue.FindesHaendelse = FindesHaendelse1;
            URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse retVal = ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).FindesHaendelse(inValue);
            return retVal.FindesHaendelseResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse> URS_Client.ServiceReferenceEVurdering.PrisModelURS.FindesHaendelseAsync(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest request) {
            return base.Channel.FindesHaendelseAsync(request);
        }
        
        public System.Threading.Tasks.Task<URS_Client.ServiceReferenceEVurdering.FindesHaendelseResponse> FindesHaendelseAsync(URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequestType FindesHaendelse) {
            URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest inValue = new URS_Client.ServiceReferenceEVurdering.FindesHaendelseRequest();
            inValue.FindesHaendelse = FindesHaendelse;
            return ((URS_Client.ServiceReferenceEVurdering.PrisModelURS)(this)).FindesHaendelseAsync(inValue);
        }
    }
}
